---
title: "Faculty Load Validation"
runtime: shiny
output: html_document
---

<style>
  .main-container {
    max-width: none;
  }
</style>

```{r setup, echo=FALSE, include=FALSE}
  library(DT)
  library(tidyverse)
  source(here::here('rscripts', 'data_io_util.R'))
  source(here::here('rscripts', 'tile_util.R'))
  # Set this to TRUE to manually perform data refresh.
  # Note that this might slow down load time greatly.
  # So make sure to set it back to FALSE before republishing.
  reload_data <- FALSE
  if (reload_data) {
    faculty_load_df <- get_data_from_sql("faculty_load.sql")
    save_data_as_rds(faculty_load_df, "faculty_load.rds")
  }
  faculty_load_df <- load_data_from_rds("faculty_load.rds")
```

```{r mung, echo=FALSE, include=FALSE}
  individual_search_df <- faculty_load_df %>%
        mutate( course_label=paste0(course_title, " ",
                                   course_number, "-",
                                   course_section_number, " ",
                                   course_term ),
                instructor_info=paste0(instructor_full_name, 
                                       ' | D', 
                                       instructor_banner_id) ) %>%
        arrange(course_term_code) %>%
        select( -c(course_title, 
                   course_number, 
                   course_section_number,
                   instructor_banner_id,
                   instructor_full_name) )
  
  workload_exploration_df <- faculty_load_df %>%
    group_by(instructor_full_name, 
             instructor_banner_id, 
             course_term,
             instructor_assignment_status,
             instructor_assignment_rank) %>%
    summarize(workload=sum(instructor_assignment_workload),
              overload=sum(instructor_assignment_overload),
              courses_taught=n_distinct(course_crn),
              students=sum(course_student_count), 
              enrolled_credit_hours=sum(course_enrolled_credit_hours),
              fte=round( sum(course_enrolled_credit_hours)/12 ) )
  
  all_terms <- sort(unique(faculty_load_df$course_term))
```

# {.tabset}
## Workload Exploration

```{r workload_exploration_ui, echo=FALSE}
  h3("Workload Summary")
  p("Select rows to expand and see more details in the 'Courses Taught' table below.")
  pickerInput("terms_selection_workload_exploration",  "Terms Selection",
              all_terms,
              options=list(`actions-box`=TRUE, `live-search`=TRUE),
              multiple=TRUE,
              selected=all_terms) 
  DT::dataTableOutput("workload_summary_table") 
  h3("Courses Taught")
  DT::dataTableOutput("workload_expansion_table")
```

```{r workload_exploration_server, echo=FALSE}
  workload_exploration_df_reactive <- reactive({
    workload_exploration_df %>%
      filter(course_term %in% input$terms_selection_workload_exploration)
  })
  output$workload_summary_table <- DT::renderDataTable(workload_exploration_df_reactive(),
                     extensions=c('Buttons', 'FixedColumns'),
                     options=list( pageLength=10,
                                   dom='Bfrtip',
                                   buttons=c('csv', 'excel'),
                                   scrollX = TRUE,
                                   scrollCollapse = TRUE
                                  ),
                     rownames=FALSE)
  expansion_df <- reactive({
    person_selection <- workload_exploration_df[input$workload_summary_table_rows_selected,]$instructor_banner_id
    term_selection <- workload_exploration_df[input$workload_summary_table_rows_selected,]$course_term
    faculty_load_df %>%
      #filter(instructor_banner_id %in% person_selection &
      #       course_term %in% term_selection)
      filter(paste(instructor_banner_id, course_term) %in% paste(person_selection, term_selection))
  })
  output$workload_expansion_table <- DT::renderDataTable( expansion_df() ,
                     extensions=c('Buttons', 'FixedColumns'),
                     options=list( pageLength=10,
                                   dom='Bfrtip',
                                   buttons=c('csv', 'excel'),
                                   scrollX = TRUE,
                                   scrollCollapse = TRUE
                                  ),
                     rownames=FALSE)
```

## Search by Individual
```{r individual_search_ui, echo=FALSE}
    fluidRow( 
      column(3,
             uiOutput('college_selection_ui'),
             uiOutput('faculty_selection_ui'),
             uiOutput('terms_selection_ui')
      ),
      column(6,
        uiOutput('individual_search_tiles')
      )
    )
```

```{r individual_search_server, echo=FALSE}
  output$college_selection_ui <- renderUI({
    colleges <- individual_search_df$instructor_assignment_college %>%
      unique() %>%
      sort()
    pickerInput("college_selection",  "College Selection", 
                colleges, 
                options=list(`actions-box`=TRUE, `live-search`=TRUE), 
                multiple=FALSE)
  })
  output$faculty_selection_ui <- renderUI({
    faculty_base <- individual_search_df %>%
      filter( instructor_assignment_college %in% input$college_selection )
    faculty <- faculty_base$instructor_info %>%
      unique() %>%
      sort()
    pickerInput("faculty_selection",  "Faculty Selection", 
                faculty, 
                options=list(`actions-box`=TRUE, `live-search`=TRUE), 
                multiple=FALSE)
  })
  output$terms_selection_ui <- renderUI({
    terms_base <- individual_search_df %>%
      filter( instructor_assignment_college %in% input$college_selection &
              instructor_info %in% input$faculty_selection) %>%
              arrange(course_term_code)
    terms <- terms_base$course_term %>%
      unique()
    pickerInput("terms_selection",  "Terms Selection", 
                terms, 
                options=list(`actions-box`=TRUE, `live-search`=TRUE), 
                multiple=TRUE,
                selected=terms)
  })
  tiles_df <- reactive({
    req(input$college_selection,
        input$faculty_selection,
        input$terms_selection)
    individual_search_df %>%
      filter( instructor_assignment_college %in% input$college_selection &
              instructor_info %in% input$faculty_selection &
              course_term %in% input$terms_selection )
  })
  output$individual_search_tiles <- renderUI({
    generate_tiles(tiles_df(),
                   tiles_name="Courses",
                   title_col="instructor_info",
                   label_col="course_label")
  })
```

## Full Dataset
```{r full_dataset_table, echo=FALSE}
  renderDataTable({
      table <- DT::datatable(faculty_load_df,
                     extensions=c('Buttons', 'FixedColumns'),
                     options=list( pageLength=15,
                                   dom='Bfrtip',
                                   buttons=c('csv', 'excel'),
                                   scrollX = TRUE,
                                   scrollCollapse = TRUE
                                  ),
                     rownames=FALSE)
      return(table)
    },
    # allows for download of all data in datatable (not just the current page)
    server=FALSE)
```


## SQL 
```{r sql_code, echo=FALSE}
query <- read_file( here::here("sql", "faculty_load.sql") )
conn <- get_conn(dsn="BRPT") 
```

```{sql, connection=conn, code=query, eval=FALSE}
```
